name: Tests
on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - master
jobs:
  tests:
    strategy:
      matrix:
        node: [14.x, 15.x]
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - uses: microsoft/playwright-github-action@v1
    - run: npm test
